import sqlite3
conn=sqlite3.connect('assignment16.db')
print("NEW DATABASE CREATED")
#conn.execute("DROP TABLE TITLE")
conn.execute('''CREATE TABLE BOOKS(BOOKID INT PRIMARY KEY NOT NULL,TITLEID INT NOT NULL, LOCATION TEXT NOT NULL, GENRE TEXT NOT NULL);''')
conn.execute('''CREATE TABLE TITLE(TITLEID INT  NOT NULL,TITLE TEXT NOT NULL, ISBN TEXT NOT NULL, PUBLISHERID INT  NOT NULL,PUBLISHERYEAR INT NOT NULL);''')
conn.execute('''CREATE TABLE AUTHORTITLE(AUTHORTITLEID INT  NOT NULL,AUTHORID INT NOT NULL,TITLEID INT NOT NULL);''')
conn.execute('''CREATE TABLE PUBLISHERS(PUBLISHERID INT  NOT NULL,NAME TEXT NOT NULL, STREETADDR TEXT NOT NULL, SUITENO INT  NOT NULL,ZIPCODEID INT NOT NULL);''')
conn.execute('''CREATE TABLE AUTHORS(AUTHORID INT  NOT NULL,FNAME TEXT NOT NULL, MNAME TEXT NOT NULL, LNAME TEXT  NOT NULL);''')
conn.execute('''CREATE TABLE ZIPCODES(ZIPCODEID INT  NOT NULL,CITY TEXT NOT NULL,STATE TEXT NOT NULL, ZIPCODE INT  NOT NULL);''')

print("ALL TABLES CREATED")

conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (4566,220,'PUNJAB','THRILLER'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (4255,203,'SHIMLA','THRILLER'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (5596,504,'HP','COMEDY'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (7400,1300,'DELHI','ROMCOM'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (8505,3250,'CHD','HORROR'); ''')
conn.execute('''INSERT INTO BOOKS(BOOKID, TITLEID,LOCATION,GENRE) VALUES (1020,2956,'PUNJAB','THRILLER'); ''')


conn.execute('''INSERT INTO TITLE(TITLEID,TITLE,ISBN,PUBLISHERID,PUBLISHERYEAR) VALUES (7280,'LEGEND',90,'89',2011); ''')
conn.execute('''INSERT INTO TITLE(TITLEID,TITLE,ISBN,PUBLISHERID,PUBLISHERYEAR) VALUES (778,'CINDER',95,'49',2012); ''')


conn.execute('''INSERT INTO AUTHORTITLE(AUTHORTITLEID,AUTHORID,TITLEID) VALUES (98,55,45); ''')
conn.execute('''INSERT INTO AUTHORTITLE(AUTHORTITLEID,AUTHORID,TITLEID) VALUES (89,65,77); ''')

conn.execute('''INSERT INTO PUBLISHERS(PUBLISHERID,NAME,STREETADDR,SUITENO,ZIPCODEID) VALUES (9,'QWERTY','ASDFG',65,8000); ''')
conn.execute('''INSERT INTO PUBLISHERS(PUBLISHERID,NAME,STREETADDR,SUITENO,ZIPCODEID) VALUES (90,'QWERTYASDFGH','QWERTYASDFG',655,80500); ''')

conn.execute('''INSERT INTO AUTHORS(AUTHORID,FNAME,MNAME,LNAME) VALUES (15,'HARMAN','PREET','VIRDI'); ''')
conn.execute('''INSERT INTO AUTHORS(AUTHORID,FNAME,MNAME,LNAME) VALUES (16,'AARUSHI','','SHARMA'); ''')

conn.execute('''INSERT INTO ZIPCODES(ZIPCODEID,CITY,STATE,ZIPCODE) VALUES (144012,'JALANDHAR','PUNJAB',141003); ''')
conn.execute('''INSERT INTO ZIPCODES(ZIPCODEID,CITY,STATE,ZIPCODE) VALUES (171001,'SHIMLA','HP',177203); ''')

cursor=conn.execute("SELECT * FROM BOOKS;")
for row in cursor:
    print("BOOKID= ", row[0])
    print("TITLE= ", row[1])
    print("LOCATION= ", row[2])
    print("GENRE= ", row[3])
    print("")


conn.execute("UPDATE BOOKS SET LOCATION ='THE WHITE TIGER' WHERE BOOKID = '8659';")
conn.execute("UPDATE BOOKS SET LOCATION ='THE LOWLAND' WHERE BOOKID = '4562';")
cursor=conn.execute("SELECT * FROM BOOKS;")
for row in cursor:
    print("BOOKID= ", row[0])
    print("TITLE= ", row[1])
    print("LOCATION= ", row[2])
    print("GENRE= ", row[3])
    print("")